name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and test project
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: 0.7.2

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Install project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: uv run pytest tests
